# Generated by Django 4.2.2 on 2025-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de alumnos que pueden inscribirse en el curso', verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
