# Generated by Django 4.2.2 on 2025-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_capacity_course_end_date_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('I', 'Inscripción'), ('P', 'Progreso'), ('F', 'Finalizado'), ('N', 'Nota')], default='N', max_length=1, verbose_name='Estado'),
        ),
    ]
