# Generated by Django 4.2.2 on 2025-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('I', 'Inscripción'), ('P', 'Progreso'), ('F', 'Finalizado'), ('N', 'Nota'), ('A', 'Asignacion')], default='N', max_length=1, verbose_name='Estado'),
        ),
    ]
