# Generated by Django 4.2.2 on 2023-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by_admin',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Creado por el administrador'),
        ),
    ]
