# Generated by Django 4.2.2 on 2025-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo'),
        ),
    ]
